### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by kishaningithub** [divan/depscheck#10]
Since this is a "binary only dependency" i would personally prefer having only the binary, effectively improve my CI build time 

I also suggest the awesome https://goreleaser.com/ to automate creation and publish of binaries. What do you think ?

**Comment by divan** [comment]
Hi @kishaningithub! Thanks for PR and issues. This tool is more like an experiment, which has some inherent flaws and I haven't checked it for years. It likely to give false negatives or false positives for many large projects, and I'm not sure what's the benefit into releasing binaries. Do you have specific use case for this tool and publishing binaries?

**Comment by kishaningithub** [comment]
@divan We currently use this tool generate reports about the dependencies we have in our project. So far it has been working really great doing its job in our CI pipeline. While the tool in itself runs very fast the installation via `go get` takes around 10 seconds whereas a binary installation would take only 1 second. That’s the motive.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
