### ISSUE TITLE
Omit internal packages

### ISSUE THREAD

**Issue by dAdAbird** [divan/depscheck#7]
It would be nice to be able to exclude internal packages from checks. For instance with `-omitinternal` flag

E.g. I have some small subpackages in my package for separation of logic. Think it's a modules but not dependencies.

I can make PR for that.

What do you think?

**Comment by divan** [comment]
Yep, totally make sense. I guess it should be the default behaviour.

**Comment by dAdAbird** [comment]
Fine!
So, do I take this issue?

**Comment by divan** [comment]
Yep, sure, you're more than welcome to contribute! :)

**Comment by dAdAbird** [comment]
Done

**Comment by divan** [comment]
Thank you!
